#!/bin/bash

set -eu

echo "Checking DB connection ..."

i=0
until [ $i -ge 10 ]
do
  nc -z recipes_db 3306 && break

  i=$(( i + 1 ))

  echo "$i: Waiting for DB 2 second ..."
  sleep 2
done

if [ $i -eq 10 ]
then
  echo "DB connection refused, terminating ..."
  exit 1
fi

echo "DB is up ..."
