framework:
  cache:
    default_redis_provider: app.redis_cache_provider
    pools:
      doctrine.second_level_cache_pool:
        adapters:
          - cache.adapter.redis
      cache.default_pool:
        adapters:
          - cache.adapter.redis

