doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        types:
          uuid_string: App\Shared\Infrastructure\Doctrine\Type\UuidType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        second_level_cache:
            region_cache_driver:
                type: pool
                pool: cache.default_pool
            enabled: true
        metadata_cache_driver:
            type: pool
            pool: cache.default_pool
        result_cache_driver:
            type: pool
            pool: cache.default_pool
        query_cache_driver:
            type: pool
            pool: cache.default_pool
        mappings:
            Auth:
              is_bundle: false
              dir: '%kernel.project_dir%/src/Auth/Domain'
              prefix: 'App\Auth\Domain'
            Recipes:
              is_bundle: false
              dir: '%kernel.project_dir%/src/Cookery/Recipes/Domain'
              prefix: 'App\Cookery\Recipes\Domain'
            FavoriteRecipes:
              is_bundle: false
              dir: '%kernel.project_dir%/src/Cookery/FavoriteRecipes/Domain'
              prefix: 'App\Cookery\FavoriteRecipes\Domain'
            Ingredients:
              is_bundle: false
              dir: '%kernel.project_dir%/src/Cookery/Ingredients/Domain'
              prefix: 'App\Cookery\Ingredients\Domain'
            Measures:
              is_bundle: false
              dir: '%kernel.project_dir%/src/Cookery/Measures/Domain'
              prefix: 'App\Cookery\Measures\Domain'
            Products:
              is_bundle: false
              dir: '%kernel.project_dir%/src/Cookery/Products/Domain'
              prefix: 'App\Cookery\Products\Domain'
            ProductCategories:
              is_bundle: false
              dir: '%kernel.project_dir%/src/Cookery/ProductCategories/Domain'
              prefix: 'App\Cookery\ProductCategories\Domain'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
