fos_rest:
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations
  format_listener:
    rules:
      - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
