security:
  enable_authenticator_manager: true

  password_hashers:
    App\Auth\Domain\User:
      algorithm: auto

  providers:
    doctrine_user_provider:
      entity:
        class: App\Auth\Domain\User
        property: email

  firewalls:
    api:
      pattern: ^/api
      stateless: true
      entry_point: jwt
      json_login:
        check_path: /api/v1/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      jwt: ~
      refresh_jwt:
        check_path: /api/v1/token/refresh
        provider: doctrine_user_provider
      logout:
        path: api_token_invalidate

  access_control:
    - { path: ^/api/v1/(login|token/refresh|register), roles: PUBLIC_ACCESS }
    - { path: ^/api/v1, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      App\Auth\Domain\User:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
