#!/usr/bin/env bash

composer install --no-scripts --no-interaction
composer dump-autoload

php bin/console doctrine:database:create --if-not-exists
php bin/console doctrine:migrations:migrate --no-interaction
php bin/console doctrine:database:create --if-not-exists --env=test
php bin/console doctrine:migrations:migrate --no-interaction --env=test

php bin/console lexik:jwt:generate-keypair

php-fpm
