version: "3"
services:
  recipes_php:
    build:
      context: ./
      target: php
      dockerfile: ./docker/php/Dockerfile
    entrypoint: "./docker-entrypoint-dev"
    working_dir: /application
    depends_on:
      - recipes_db
      - redis
    volumes:
      - .:/application
      - ./docker/php/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
      - ./etc/infrastructure/php/conf.d/xdebug.ini:/etc/php/8.1/fpm/conf.d/20-xdebug.ini
      - ./etc/infrastructure/php/conf.d/xdebug.ini:/etc/php/8.1/cli/conf.d/20-xdebug.ini
      - /tmp/xdebug:/tmp/xdebug
    networks:
      proxy:
        ipv4_address: 10.200.18.3

  recipes_nginx:
    build:
      context: ./
      target: nginx
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - recipes_php
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.recipes_backend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.recipes_backend.tls.certresolver=lets_encrypt_resolver"
    networks:
      proxy:
        ipv4_address: 10.200.18.2

  recipes_db:
    image: mysql:8.0.31
    volumes:
      - ./../data/recipes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=recipes
      - MYSQL_HOST=127.0.0.1
    networks:
      proxy:
        ipv4_address: 10.200.18.4

  redis:
    image: redis:6.2.5
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      proxy:
        ipv4_address: 10.200.18.5

networks:
  proxy:
    external: true
