version: "3"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_recipes
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.recipes_backend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.recipes_backend.tls.certresolver=lets_encrypt_resolver"
    networks:
      proxy:
        ipv4_address: 10.200.18.2

  php_recipes:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    image: php:latest
    working_dir: /application
    depends_on:
      - db
    volumes:
      - .:/application
      - ./docker/php/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
    networks:
      proxy:
        ipv4_address: 10.200.18.3

  db:
    image: mysql
    volumes:
      - ./../data/recipes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=recipes
      - MYSQL_HOST=127.0.0.1
    networks:
      proxy:
        ipv4_address: 10.200.18.4

networks:
  proxy:
    external: true
