version: "3"
services:
  recipes_php:
    build:
      context: ./
      target: php
      dockerfile: ./docker/php/Dockerfile-prod
    image: ghcr.io/dominx99/recipes-php
    working_dir: /application
    depends_on:
      - recipes_db
    networks:
      proxy:
        ipv4_address: 10.200.18.2

  recipes_nginx:
    build:
      context: ./
      target: nginx
      dockerfile: ./docker/php/Dockerfile-prod
    image: ghcr.io/dominx99/recipes-nginx
    depends_on:
      - recipes_php
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.recipes_backend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.recipes_backend.tls.certresolver=lets_encrypt_resolver"
    networks:
      proxy:
        ipv4_address: 10.200.18.3

  recipes_db:
    image: mysql
    volumes:
      - ./../data/recipes/mysql:/var/lib/mysql
    secrets:
      - recipes_db_root_password
    environment:
      - MYSQL_ROOT_PASSWORD=/run/secrets/recipes_db_root_password
      - MYSQL_DATABASE=recipes
      - MYSQL_HOST=127.0.0.1
    networks:
      proxy:
        ipv4_address: 10.200.18.4

secrets:
  recipes_db_root_password:
    external: true

networks:
  proxy:
    external: true
