version: "3"
services:
  recipes_php:
    build:
      context: ./
      target: php
      dockerfile: ./docker/php/Dockerfile-prod
    image: ghcr.io/dominx99/recipes-php
    working_dir: /application
    depends_on:
      - db
    volumes:
      - ./docker/php/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
    environment:
      PHP_EXTENSION_REDIS: 1
      PHP_EXTENSION_GETTEXT: 1
      PHP_EXTENSION_PDO: 1
      PHP_EXTENSION_PDO_MYSQL: 1
      PHP_EXTENSION_LDAP: 1
      PHP_EXTENSION_INTL: 1
    networks:
      proxy:
        ipv4_address: 10.200.18.2

  nginx:
    build:
      context: ./
      target: nginx
      dockerfile: ./docker/php/Dockerfile-prod
    image: ghcr.io/dominx99/recipes-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - recipes_php
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.recipes_backend.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.recipes_backend.tls.certresolver=lets_encrypt_resolver"
    networks:
      proxy:
        ipv4_address: 10.200.18.3

  db:
    image: mysql
    volumes:
      - ./../data/recipes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=recipes
      - MYSQL_HOST=127.0.0.1
    networks:
      proxy:
        ipv4_address: 10.200.18.4

networks:
  proxy:
    external: true
