controllers:
  resource: ../src/Cookery/**/Http/*
  type: attribute

users_controllers:
  resource: ../src/Auth/Http/
  type: attribute

api_login_check:
  path: /api/v1/login

api_refresh_token:
  path: /api/v1/token/refresh

api_token_invalidate:
  path: /api/v1/token/invalidate
