parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Shared\Infrastructure\Symfony\ApiExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onException }

  App\Shared\Http\Symfony\RequestResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 50 }

  app.redis_cache_provider:
    class: Doctrine\Common\Cache\RedisCache
    factory: ['App\Shared\Infrastructure\Cache\Redis\RedisProviderFactory', 'create']
    arguments:
      $host: '%env(REDIS_HOST)%'
      $port: '%env(int:REDIS_PORT)%'
      $databaseNumber: '%env(int:REDIS_DATABASE_NUMBER)%'
      $prefix: '%env(REDIS_PREFIX)%'
