name: Build

on:
  push:
    branches:
      - '**'
      - '!main'
  workflow_call:
    secrets:
      GHCR_TOKEN:
        required: true
      VAULT_TOKEN:
        required: true

permissions:
  contents: read
jobs:
  main:
    runs-on: ubuntu-latest
    name: Build application
    steps:
      -
        name: Checkout to current branch
        uses: actions/checkout@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Import Secrets from self hosted vault
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault.chylo.pl:8880
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/recipes/backend DOMAIN | DOMAIN ;
            secret/data/recipes/backend APP_ENV | APP_ENV ;
            secret/data/recipes/backend APP_SECRET | APP_SECRET ;
            secret/data/recipes/backend DATABASE_URL | DATABASE_URL ;
            secret/data/recipes/backend CORS_ALLOW_ORIGIN | CORS_ALLOW_ORIGIN ;
            secret/data/recipes/backend DATABASE_PASSWORD | DATABASE_PASSWORD ;

      - name: Copy application environment to .env file
        run: 'envsubst < .env.tmpl > .env'

      - name: Copy database env from environment variables
        run: 'envsubst < .env.db.tmpl > database.env'

      - name: Run multiarch qemu user static
        run: 'docker run --rm --privileged multiarch/qemu-user-static --reset -p yes'

      -
        name: Build and push docker images
        uses: docker/bake-action@v2
        with:
          push: true
          files: 'docker-compose.prod.yml'
          targets: 'recipes_php,recipes_nginx'
          set: |
            recipes_php.platform=linux/arm64
            recipes_nginx.platform=linux/arm64
