name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
jobs:
  my-instances:
    runs-on: ubuntu-latest
    name: List the display name and shape of the instances in my compartment
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'oracle-1'
          path: ''
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Import Secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault.chylo.pl:8880
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/recipes/backend DOMAIN | DOMAIN ;
            secret/data/recipes/backend APP_ENV | APP_ENV ;
            secret/data/recipes/backend APP_SECRET | APP_SECRET ;
            secret/data/recipes/backend DATABASE_URL | DATABASE_URL ;
            secret/data/recipes/backend CORS_ALLOW_ORIGIN | CORS_ALLOW_ORIGIN ;

      - name: Copy env
        run: 'envsubst < .env.tmpl > .env'

      -
        name: Build and push
        uses: docker/bake-action@v2
        with:
          push: true
          files: 'docker-compose.prod.yml'
          targets: 'recipes_php,recipes_nginx'
          set: |
            recipes_php.platform=linux/arm64
            recipes_nginx.platform=linux/arm64

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.INSTANCE_HOST }}
          key: ${{ secrets.INSTANCE_PRIVATE_KEY }}
          username: opc
          source: "docker-compose.prod.yml"
          target: "/home/opc/workspace/recipes/api/docker-compose.yml"

      - name: 'Start App'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_HOST }}
          key: ${{ secrets.INSTANCE_PRIVATE_KEY }}
          username: opc
          script: |
            cd workspace/recipes/api
            docker-compose up -d
