name: Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
jobs:
  build:
    uses: dominx99/recipes-backend/.github/workflows/build.yml@main
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy application
    steps:
      -
        name: Checkout to current branch
        uses: actions/checkout@v3

      - name: Import Secrets from self hosted vault
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault.chylo.pl:8880
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/data/recipes/backend DOMAIN | DOMAIN ;
            secret/data/recipes/backend APP_ENV | APP_ENV ;
            secret/data/recipes/backend APP_SECRET | APP_SECRET ;
            secret/data/recipes/backend DATABASE_URL | DATABASE_URL ;
            secret/data/recipes/backend CORS_ALLOW_ORIGIN | CORS_ALLOW_ORIGIN ;
            secret/data/recipes/backend DATABASE_PASSWORD | DATABASE_PASSWORD ;
            secret/data/recipes/backend JWT_SECRET_KEY | JWT_SECRET_KEY ;
            secret/data/recipes/backend JWT_PUBLIC_KEY | JWT_PUBLIC_KEY ;
            secret/data/recipes/backend JWT_PASSPHRASE | JWT_PASSPHRASE ;
            secret/data/recipes/backend REDIS_HOST | REDIS_HOST ;
            secret/data/recipes/backend REDIS_PORT | REDIS_PORT ;
            secret/data/recipes/backend REDIS_PREFIX | REDIS_PREFIX ;
            secret/data/recipes/backend REDIS_DATABASE_NUMBER | REDIS_DATABASE_NUMBER ;

      - name: Copy application environment to .env file
        run: 'envsubst < .env.tmpl > .env'

      - name: Copy database env from environment variables
        run: 'envsubst < .env.db.tmpl > database.env'

      - name: Copy docker-compose to the OCI instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.INSTANCE_HOST }}
          key: ${{ secrets.INSTANCE_PRIVATE_KEY }}
          username: root
          source: "docker-compose.prod.yml,database.env,.env"
          target: "/root/workspace/recipes/api/"

      - name: Start application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.INSTANCE_HOST }}
          key: ${{ secrets.INSTANCE_PRIVATE_KEY }}
          username: root
          script: |
            cd workspace/recipes/api
            mv docker-compose.prod.yml docker-compose.yml
            docker-compose pull
            docker-compose up -d --no-build
